### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by D1monUA** [kuzin2006/hass_save_eco_bot_sensor#4]
Здравствуйте, не работает сенсор, выдает в логах ошибку:
Как можно пофиксить? 

Logger: homeassistant.components.sensor
Source: custom_components/save_eco_bot/sensor.py:124
Integration: Сенсор ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 00:38:05 (1 occurrences)
Last logged: 00:38:05

Error while setting up save_eco_bot platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/save_eco_bot/sensor.py", line 263, in async_setup_platform
    sensors += [SaveEcoBotSensor(client=_client, sensor_model=s) for s in station.sensors()]
  File "/config/custom_components/save_eco_bot/sensor.py", line 124, in sensors
    "updated_at": datetime.datetime.strftime(p.time, "%d.%m.%Y, %H:%M:%S"),
TypeError: descriptor 'strftime' for 'datetime.date' objects doesn't apply to a 'NoneType' object

**Comment by VahaC** [comment]
https://github.com/andr7000/hass_save_eco_bot_sensor
