### ISSUE TITLE
Stopped working with Home Assistant 2022.12.1

### ISSUE THREAD

**Issue by TetianaKolpakova** [kuzin2006/hass_save_eco_bot_sensor#5]
Hi @kuzin2006, since latest HA update this module stopped working completely and throws this error
I'm not very good at Pyton, can you advice how to fix it?
```

Error while setting up save_eco_bot platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/save_eco_bot/sensor.py", line 263, in async_setup_platform
    sensors += [SaveEcoBotSensor(client=_client, sensor_model=s) for s in station.sensors()]
  File "/config/custom_components/save_eco_bot/sensor.py", line 136, in sensors
    deprecated=datetime.datetime.now() - p.time > datetime.timedelta(hours=SENSOR_DEPRECATION_HOURS)
TypeError: can't subtract offset-naive and offset-aware datetimes
```

**Comment by VahaC** [comment]
https://github.com/andr7000/hass_save_eco_bot_sensor

**Comment by AmaruIT** [comment]
> https://github.com/andr7000/hass_save_eco_bot_sensor

Есть ещё какие-то варианты? Ни одна интеграция не работает. Последняя, но тему с ошибкой создать не могу почему-то там.  https://github.com/Port2all/2025_hass_save_eco_bot_sensor
В журнале предупреждение, сенсоры не добавляются.
Регистратор: py.warnings
Источник: custom_components/save_eco_bot2/sensor.py:4
интеграция: save_eco_bot2 ([документация](https://github.com/andr7000/hass_save_eco_bot_sensor/blob/master/README.md), [проблемы](https://github.com/andr7000/hass_save_eco_bot_sensor/issues))
Первое сообщение: 14:08:31 (1 сообщений)
Последнее сообщение: 14:08:31
/usr/local/lib/python3.13/site-packages/pydantic/_migration.py:283: UserWarning: `pydantic.error_wrappers:ValidationError` has been moved to `pydantic:ValidationError`. warnings.warn(f'`{import_path}` has been moved to `{new_location}`.')

**Comment by medvedev-dy** [comment]
@AmaruIT https://github.com/uhodav/ha_saveecobot
